function set_axis_properties(PlotProps)

 set(gca, 'FontName', PlotProps.Text.FontName, ...
     'FontSize', PlotProps.Text.AxisSize, ...
     'Color', PlotProps.Color.Background, ...
     'TickDir',PlotProps.Axes.TickDir)

 title('', 'FontSize',PlotProps.Text.TitleSize)